apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-k8s-app
  namespace: java-k8s
  labels:
    app: java-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-k8s-app
  template:
    metadata:
      labels:
        app: java-k8s-app
    spec:
      containers:
        - name: my-app
          image: ghcr.io/rodrigonascimento001/java-k8s/java-k8s:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:          # (1) limites de recursos → ajuda o scheduler
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:      # (2) healthcheck básico
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:     # (3) garante que só entra no load balancer se estiver pronto
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
