apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: my-app
    newName: ghcr.io/rodrigonascimento001/my-repo/my-app
    newTag: latest
